[1.21.x] Equipment Integration Abstraction and Accessories Integration
ochotonida/artifacts pull request #336
Opened 2024-11-01 00:46 UTC by Dragon-Seeker

This PR aims to add native support for Accessories by reworking the underlying API to allow for the implementation of other Accessories API based on extendable class.

Other Changes
- Move trinkets to common to allow for such to work with Sinytra connector loading trinkets
- Allow for any Artifact item to be toggle its rendering (Could be changed to only if needed but it is unknown how to handle such within the config)

Reason: Issues with trinkets and curios implementation lead to issues with the compat layers that could be resolved but I decided to abstract away the equipment integration API to allow for others to add support for API if the need for such arises.

2025-03-12 18:21 UTC, ochotonida requested changes
Most of this looks good. With both Accessories and Transmog being an option for toggleable cosmetics for Fabric, I don't think the right-click system is needed anymore, so moving it to common wasn't necessary. You can leave it as is in your PR, I'll strip it out myself after merging.

2025-03-12 18:21 UTC, ochotonida commented on neoforge/src/main/java/artifacts/neoforge/ArtifactsNeoForgeClient.java
> -        }
Was removing this intentional? The method still exists but I don't see it getting called anywhere. While you're at it, you should also double check that non-player entity rendering works with Accessories, you can bump up the `entityEquipmentChance` value in the config for the second one.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/client/CosmeticsHelper.java
>      }
Most of the cosmetics toggling code was moved to common, but this still only gets called on the Fabric side of things.

I'm not sure how I feel about adding the right-click cosmetics toggling mechanic to NeoForge for the small amount of users that want to use Trinkets with Synitra. Having two separate ways to toggle cosmetics would just be confusing for everyone else.
With Transmog supporting Trinkets in 1.21, I don't think the system is needed anymore. You can leave it as is in your PR though.

2025-03-12 18:21 UTC, ochotonida commented on fabric/src/main/java/artifacts/fabric/mixin/compat/trinkets/client/PlayerRendererMixin.java
This class didn't move to common, so gloves will not render in first person for people running Trinkets on NeoForge. 
I also don't see the first person glove rendering implemented for Accessories.
ArmRenderHandler handles first person glove rendering on NeoForge using RenderArmEvent, you should have something similar for Trinkets/Accessories and factor out the common code.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/platform/PlatformHelper.java
This interface is used exclusively for platform-specific code, some of the methods in this interface are no longer being overridden and can be inlined or moved somewhere else.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/integration/EquipmentIntegrationUtils.java
> +        var name = integration.name();
I prefer explicit type declarations for clarity.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/integration/EquipmentIntegrationUtils.java
> +        if (INTEGRATIONS.containsKey(name)) throw new IllegalStateException("Duplicate Equipment Integration detected! [Name: " + name + "]");
Please use braces and put the body on the next line, here and a couple of other places.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/integration/VanillaEquipmentIntegration.java
> +        return "vanilla";
It's a personal choice, but I think "minecraft" is more appropriate here.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/integration/client/ClientEquipmentIntegrationUtils.java
> +        if (INTEGRATIONS.containsKey(name)) throw new IllegalStateException("Duplicate Equipment Integration detected! [Name: " + name + "]");
The error message for duplicate client and non-client integrations is the same

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/integration/EquipmentIntegrationUtils.java
> +    }
This can be moved to ClientEquipmentIntegrationUtils

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/integration/BaseEquipmentIntegration.java
> +    }
I think it's better to inline this method where it's called, and turn this class into an interface (same for ClientBaseEquipmentIntegration). You can also drop "Base" from the name.

2025-03-12 18:21 UTC, ochotonida commented on common/src/main/java/artifacts/platform/PlatformHelper.java
> +    }
I don't think keeping a public static instance in each integration class is necessary, you can instantiate them here.

2025-03-17 05:59 UTC, Dragon-Seeker commented on neoforge/src/main/java/artifacts/neoforge/ArtifactsNeoForgeClient.java
> -        }
> Was removing this intentional?

Nope that was an oversight on my part, will reimplement such.

> ...double check that non-player entity rendering works with Accessories...

Accessories has support for all entities rather than just players but I can test such just to confirm and will post a image for such.

2025-03-17 05:59 UTC, Dragon-Seeker commented on fabric/src/main/java/artifacts/fabric/mixin/compat/trinkets/client/PlayerRendererMixin.java
> This class didn't move to common, so gloves will not render in first person for people running Trinkets on NeoForge.

Ah that is a problem that will need to be adjusted for Trinkets, Accessories providers a built-in method to render Accessories in First person but such needs to be implemented which I will do. I look into refactoring such to be callable from either the mixin on fabric or the event on neoforge while using Accessories API for such.

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/platform/PlatformHelper.java
> +    }
True will adjust such

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/platform/PlatformHelper.java
True, will do such.

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/integration/client/ClientEquipmentIntegrationUtils.java
> +        if (INTEGRATIONS.containsKey(name)) throw new IllegalStateException("Duplicate Equipment Integration detected! [Name: " + name + "]");
Ah, the good old copy-and-paste mess is up. I really wish I unlearned such keybind sometimes. Will adjust such message

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/integration/EquipmentIntegrationUtils.java
> +    }
Got it

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/integration/EquipmentIntegrationUtils.java
> +        var name = integration.name();
Sorry, my bad. Such will be adjusted.

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/integration/EquipmentIntegrationUtils.java
> +        if (INTEGRATIONS.containsKey(name)) throw new IllegalStateException("Duplicate Equipment Integration detected! [Name: " + name + "]");
Got it.

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/integration/BaseEquipmentIntegration.java
> +    }
Honestly don't really understand why I did such in the first place... but I will adjust such.

2025-03-17 05:59 UTC, Dragon-Seeker commented on common/src/main/java/artifacts/integration/VanillaEquipmentIntegration.java
> +        return "vanilla";
Got it.

2025-03-17 06:09 UTC, Dragon-Seeker commented
> With both Accessories and Transmog being an option for toggleable cosmetics for Fabric, I don't think the right-click system is needed anymore... I'll strip it out myself after merging.

I decided not to take such action directly as I did not want to take any feature away if nothing was there for people using trinkets so I decided to merge such into common and have you decided about removing it or not.

I have adjusted such based on your preferences and sorry for the delay as I got busy with some stuff.

2025-03-17 12:11 UTC, ochotonida commented
Looks good, thanks! I'll do a bit more testing myself, and release this in the next update either today or later this week.

2025-03-17 12:11 UTC, merged